ANSI_RESERVED_WORDS = {
    "SELECT", "FROM", "WHERE", "GROUP", "BY", "HAVING",
    "ORDER", "INSERT", "INTO", "VALUES", "UPDATE", "SET", 
    "DELETE", "CREATE", "TABLE", "ALTER", "DROP", "TRUNCATE",
    "PRIMARY", "KEY", "FOREIGN", "REFERENCES", "UNIQUE", 
    "NOT", "NULL", "CHECK", "DEFAULT", "JOIN", "INNER", 
    "LEFT", "RIGHT", "FULL", "OUTER", "ON", "UNION", "ALL", 
    "DISTINCT", "AS", "AND", "OR", "IN", "EXISTS", "BETWEEN", 
    "LIKE", "CASE", "WHEN", "THEN", "ELSE", "END", "VIEW", 
    "INDEX", "DATABASE", "SCHEMA", "GRANT", "REVOKE", 
    "COMMIT", "ROLLBACK", "TRANSACTION"
}

ANSI_DATA_TYPES = {"INT", "INTEGER", "VARCHAR", "TEXT", "DATE", "DECIMAL", "BOOLEAN"}
